# Generated by Django 3.2.12 on 2022-03-23 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Course Name')),
                ('semesters', models.CharField(max_length=250)),
                ('fees', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='College Name')),
                ('place', models.CharField(max_length=250)),
                ('phone', models.IntegerField(default=0)),
                ('address', models.CharField(max_length=350)),
                ('email', models.EmailField(blank=True, max_length=250, null=True, unique=True)),
                ('courses', models.ManyToManyField(default='', to='scholarapi.Course')),
            ],
        ),
    ]
