# Generated by Django 3.2.12 on 2022-03-27 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Course Name')),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='College Name')),
                ('place', models.CharField(max_length=250, verbose_name='Location')),
                ('address', models.CharField(max_length=350, verbose_name='Address')),
                ('affiliated_university', models.CharField(default='', max_length=200, verbose_name='Affiliated University')),
                ('fee_brochure', models.FileField(null=True, upload_to='fees/', verbose_name='Fees Brochure')),
                ('courses', models.ManyToManyField(default='', to='scholarapi.Course', verbose_name='Available Courses')),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=250, verbose_name='Last Name')),
                ('phone', models.IntegerField(default=0)),
                ('email', models.EmailField(blank=True, max_length=250, null=True, unique=True)),
                ('college', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scholarapi.college', verbose_name='College Name')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scholarapi.course', verbose_name='Course Name')),
            ],
        ),
    ]
