# Generated by Django 3.2.12 on 2022-03-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='college_image',
            field=models.FileField(null=True, upload_to='colleges/', verbose_name='College Image'),
        ),
    ]
