# Generated by Django 3.2.12 on 2022-03-23 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scholarapi', '0002_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='course',
            field=models.CharField(default='', max_length=250, verbose_name='Course Name'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='college',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scholarapi.college', verbose_name='College Name'),
        ),
    ]
