# Generated by Django 3.2.12 on 2022-03-23 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scholarapi', '0003_auto_20220324_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scholarapi.course', verbose_name='Course Name'),
        ),
    ]
