# Generated by Django 3.2.12 on 2022-03-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarapi', '0004_alter_candidate_course'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Candidate',
            new_name='Applicant',
        ),
        migrations.AlterField(
            model_name='course',
            name='fees',
            field=models.IntegerField(default=0, verbose_name='Course Fee'),
        ),
    ]
