# Generated by Django 3.2.12 on 2022-03-27 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarapi', '0005_auto_20220324_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='fee_brochure',
            field=models.FileField(null=True, upload_to='<django.db.models.fields.CharField>/'),
        ),
    ]
