# Generated by Django 3.2.12 on 2022-03-27 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarapi', '0006_course_fee_brochure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='fee_brochure',
            field=models.FileField(null=True, upload_to='fees/'),
        ),
    ]
