# Generated by Django 3.2.12 on 2022-03-27 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarapi', '0007_alter_course_fee_brochure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='fee_brochure',
        ),
        migrations.AddField(
            model_name='college',
            name='fee_brochure',
            field=models.FileField(null=True, upload_to='fees/'),
        ),
    ]
